'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import { motion } from 'framer-motion';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { ArrowRight, ArrowUpRight, Plus, ChevronDown, ChevronRight, CalendarDays, Lightbulb, CheckCheck, Users, GraduationCap, MapPin, Droplets, Sprout, BookOpen, HeartPulse, Zap, Recycle, Sparkles, ArrowUp, Clock3, Download, Layers3, CircleCheck, MoveUpRight } from 'lucide-react';
import { usePortal } from '@/components/providers/portal-provider';
import { Button } from '@/components/ui/button';

const DashboardMap = dynamic(() => import('./dashboard-map'), { ssr: false, loading: () => <div className="map-placeholder">Loading the Jharkhand challenge map…</div> });
const categoryIcons = { 'Water Resources': Droplets, Agriculture: Sprout, Education: BookOpen, Healthcare: HeartPulse, Energy: Zap, 'Waste Management': Recycle };
const roleText = { citizen: ['Your voice. Your community. Your impact.', 'Keep track of the challenges you’ve reported and the change you’re creating.'], authority: ['Let’s turn challenges into progress.', 'Review community needs, connect the right teams, and keep solutions moving.'], university: ['Great minds. Grounded solutions.', 'Bring your expertise to the challenges that matter to our communities.'], industry: ['Build partnerships that build possibility.', 'Discover where your expertise and resources can make a lasting difference.'], ngo: ['Better outcomes, together.', 'Connect your community expertise with projects ready to make a difference.'], partner: ['Build partnerships that build possibility.', 'Discover where your expertise and resources can make a lasting difference.'], admin: ['A connected ecosystem. A clearer picture.', 'Manage your innovation network and monitor progress across the state.'] };
export function StatusBadge({ status }) { const tone = status === 'Resolved' || status === 'Validated' ? 'green' : ['In progress', 'Assigned', 'Pilot testing'].includes(status) ? 'blue' : status === 'Rejected' ? 'red' : 'amber'; return <span className={`status-badge ${tone}`}><i />{status}</span>; }
export function MetricCard({ icon: Icon, label, value, note, color = 'teal', index = 0 }) { return <motion.div className="metric-card" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.05 }}><div className="metric-top"><span>{label}</span><span className={`metric-icon ${color}`}><Icon size={19} strokeWidth={1.7} /></span></div><div className="metric-value">{typeof value === 'number' ? value.toLocaleString('en-IN') : value}<svg viewBox="0 0 96 30" aria-hidden="true"><path d="M2 27 L12 22 L22 25 L31 15 L40 19 L50 10 L59 13 L70 6 L79 10 L94 2" fill="none" stroke="currentColor" strokeWidth="2" /><path d="M2 27 L12 22 L22 25 L31 15 L40 19 L50 10 L59 13 L70 6 L79 10 L94 2 L94 30 L2 30Z" fill="currentColor" opacity=".06" /></svg></div><p><span className="metric-indicator"><ArrowUpRight size={13} /></span>{note}</p></motion.div>; }
export default function Dashboard({ role }) {
  const { user, problems, loading } = usePortal();
  const [period, setPeriod] = useState('This year'); const [district, setDistrict] = useState('All districts');
  const activeRole = role || user?.role; const [heading, subtitle] = roleText[activeRole] || ['Together, for a better tomorrow.', 'Connecting communities, expertise, and ideas to create meaningful change.'];
  const scoped = activeRole === 'citizen' && user ? problems.filter(p => p.reporter?.id === user.id) : activeRole === 'university' && user ? problems.filter(p => p.assignedTo === user.organization || p.assignedOrganizationId === user.organizationId) : problems;
  const resolved = scoped.filter(p => p.status === 'Resolved');
  const active = scoped.filter(p => ['In progress', 'Assigned', 'Pilot testing', 'In development', 'Implementation'].includes(p.status));
  const people = resolved.reduce((n, p) => n + Number(p.affectedPopulation || 0), 0);
  const districtProblems = district === 'All districts' ? problems : problems.filter(p => p.district === district);
  const categoryCounts = Object.entries(problems.reduce((out, p) => ({ ...out, [p.category]: (out[p.category] || 0) + 1 }), {})).sort((a, b) => b[1] - a[1]).slice(0, 5);
  const trends = useMemo(() => { const now = new Date(); const count = period === 'Last 3 months' ? 3 : period === 'Last 6 months' ? 6 : 9; return Array.from({ length: count }, (_, i) => { const date = new Date(now.getFullYear(), now.getMonth() - count + i + 1, 1); const match = p => new Date(p.createdAt).getMonth() === date.getMonth() && new Date(p.createdAt).getFullYear() === date.getFullYear(); return { month: date.toLocaleDateString('en', { month: 'short' }), submitted: problems.filter(match).length, resolved: problems.filter(p => p.status === 'Resolved' && new Date(p.updatedAt).getMonth() === date.getMonth()).length }; }); }, [problems, period]);
  const recent = [...scoped].sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0, 4);
  const activities = problems.flatMap(p => (p.timeline || []).map(item => ({ ...item, problemId: p.id, problemTitle: p.title }))).sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 4);
  const exportOverview = () => { const rows = [['ID', 'Title', 'District', 'Category', 'Status', 'Priority'], ...scoped.map(p => [p.id, p.title, p.district, p.category, p.status, p.priority])]; const csv = rows.map(row => row.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')).join('\r\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'jharkhand-challenges.csv'; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="dashboard-page">
    <div className="page-heading dashboard-heading"><div><div className="eyebrow"><span className="live-dot" /> THE JHARKHAND INNOVATION ECOSYSTEM</div><h1>{heading}</h1><p>{subtitle}</p></div><button className="btn btn-secondary export-button" onClick={exportOverview}><Download size={16} /> Export report</button></div>
    <section className="community-hero"><div className="hero-copy"><span className="hero-kicker"><span /> PEOPLE. POSSIBILITIES. PROGRESS.</span><h2>Local challenges.<br /><em>Collective solutions.</em></h2><p>From the first report to a lasting change.<br />Be part of a better Jharkhand.</p><div className="hero-buttons"><Button asChild><Link href="/report"><Plus size={17} /> Report a problem</Link></Button><Link className="hero-secondary" href="/challenges">Explore challenges <ArrowUpRight size={16} /></Link></div><div className="hero-people"><div className="avatar-stack"><span>AS</span><span>PK</span><span>RM</span><span>+8</span></div><span>Citizens. Innovators. Changemakers.<br /><strong>One shared purpose.</strong></span></div></div><div className="hero-visual" aria-hidden="true"><div className="hero-landscape" /><div className="hero-image-shade" /><div className="hero-floating floating-top"><span className="floating-icon"><Lightbulb size={20} /></span><div><strong>Ideas meet opportunity</strong><small>Connecting expertise to real needs</small></div><span className="mini-check"><CheckCheck size={16} /></span></div><div className="hero-floating floating-bottom"><div className="floating-impact"><Sprout size={21} /></div><div><strong>Rooted in community.</strong><small>Growing through collaboration.</small></div></div><div className="hero-region"><MapPin size={15} /> JHARKHAND, INDIA</div></div></section>
    <section className="metric-grid" aria-label="Ecosystem at a glance"><MetricCard icon={Lightbulb} label="Total challenges" value={loading ? '—' : scoped.length} note="Community ideas, real possibilities" index={0} /><MetricCard icon={Layers3} label="Solutions in progress" value={loading ? '—' : active.length} note="Moving from ideas to action" color="blue" index={1} /><MetricCard icon={CircleCheck} label="Challenges resolved" value={loading ? '—' : resolved.length} note="Solutions making a difference" color="purple" index={2} /><MetricCard icon={Users} label="People impacted" value={loading ? '—' : people} note="Reported reach of resolved challenges" color="orange" index={3} /></section>
    <div className="overview-grid"><section className="card trend-card"><div className="section-heading"><div><h3>Progress at a glance</h3><p>Every challenge brings us a step forward.</p></div><label className="compact-select"><CalendarDays size={14} /><select aria-label="Trend time period" value={period} onChange={e => setPeriod(e.target.value)}><option>This year</option><option>Last 6 months</option><option>Last 3 months</option></select><ChevronDown size={13} /></label></div><div className="chart-legend"><span><i className="legend-dot teal" /> Challenges reported</span><span><i className="legend-dot light-teal" /> Challenges resolved</span></div><div className="trend-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trends} margin={{ top: 10, right: 5, bottom: 0, left: -27 }}><defs><linearGradient id="reportedGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#128675" stopOpacity={0.17} /><stop offset="100%" stopColor="#128675" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e9eeed" /><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: '#89949b' }} dy={8} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: '#89949b' }} /><Tooltip contentStyle={{ borderRadius: 10, border: '1px solid #e4eae8', fontSize: 12 }} /><Area name="Reported" type="monotone" dataKey="submitted" stroke="#0c8d7b" strokeWidth={2.5} fill="url(#reportedGradient)" /><Area name="Resolved" type="monotone" dataKey="resolved" stroke="#91baa7" strokeWidth={2} strokeDasharray="4 4" fill="transparent" /></AreaChart></ResponsiveContainer></div></section>
    <section className="card region-card"><div className="section-heading"><div><h3>Change, across Jharkhand</h3><p>Local needs. Statewide possibilities.</p></div><Link href="/challenges?view=map" className="icon-link" aria-label="Explore map"><ArrowUpRight size={19} /></Link></div><div className="region-map"><DashboardMap problems={districtProblems} /><label className="map-district-select"><MapPin size={13} /><select aria-label="Map district" value={district} onChange={e => setDistrict(e.target.value)}><option>All districts</option>{[...new Set(problems.map(p => p.district))].sort().map(name => <option key={name}>{name}</option>)}</select></label></div><div className="map-footer"><span><i className="legend-dot teal" /> Resolved</span><span><i className="legend-dot amber" /> High priority</span><Link href="/challenges?view=map">Explore map <ArrowRight size={13} /></Link></div></section></div>
    <div className="challenge-row"><section className="card recent-challenges"><div className="section-heading"><div><h3>{activeRole === 'citizen' ? 'Your recent challenges' : 'Challenges that need a hand'}</h3><p>Discover where you can make a difference.</p></div><Link className="text-link" href="/challenges">View all <ArrowRight size={14} /></Link></div><div className="table-scroll"><table className="challenge-table"><thead><tr><th>CHALLENGE</th><th>PRIORITY</th><th>STATUS</th><th aria-label="View challenge" /></tr></thead><tbody>{recent.map((problem, i) => { const Icon = categoryIcons[problem.category] || Lightbulb; return <tr key={problem.id}><td><Link href={`/challenges/${problem.id}`} className="table-challenge"><span className={`challenge-icon category-${i}`}><Icon size={20} strokeWidth={1.7} /></span><span><strong>{problem.title}</strong><small><MapPin size={11} />{problem.district}<span>·</span>{problem.category}</small></span></Link></td><td><span className={`priority-label ${problem.priority?.toLowerCase()}`}><i />{problem.priority}</span></td><td><StatusBadge status={problem.status} /></td><td><Link className="table-arrow" aria-label={`View ${problem.title}`} href={`/challenges/${problem.id}`}><ArrowUpRight size={16} /></Link></td></tr>; })}</tbody></table>{!loading && recent.length === 0 && <div className="empty-state"><Lightbulb size={28} /><h3>Your first challenge starts here</h3><p>Tell us what your community needs.</p><Link className="btn btn-primary" href="/report">Report a problem</Link></div>}</div></section><section className="card activity-card"><div className="section-heading"><h3>Making things happen</h3><span className="activity-live">Live activity</span></div><div className="activity-feed">{activities.map((activity, index) => <Link key={`${activity.problemId}-${activity.id || index}`} href={`/challenges/${activity.problemId}`} className="activity-item"><span className={`activity-symbol ${index === 0 ? 'teal' : index === 1 ? 'blue' : 'purple'}`}>{index === 0 ? <CheckCheck size={15} /> : index === 1 ? <GraduationCap size={15} /> : <Lightbulb size={15} />}</span><div><strong>{activity.title || activity.status || 'Challenge updated'}</strong><p>{activity.problemTitle}</p><small>{new Date(activity.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} <span>·</span> {activity.actor || 'Community update'}</small></div></Link>)}</div><Link href="/notifications" className="activity-all">View all activity <ArrowRight size={14} /></Link></section></div>
    <div className="bottom-grid"><section className="card categories-card"><div className="section-heading"><div><h3>Many challenges. One mission.</h3><p>Find the cause that speaks to you.</p></div><Link href="/challenges" className="text-link">Explore categories <ArrowRight size={14} /></Link></div><div className="category-tiles">{['Water Resources', 'Education', 'Agriculture', 'Healthcare', 'Environment', 'Energy'].map((category, i) => { const Icon = categoryIcons[category] || Sprout; return <Link key={category} href={`/challenges?category=${encodeURIComponent(category)}`} className="category-tile"><span className={`category-tile-icon category-${i % 4}`}><Icon size={23} strokeWidth={1.6} /></span><strong>{category}</strong><small>{problems.filter(p => p.category === category).length} challenges <ArrowUpRight size={11} /></small></Link>; })}</div></section><section className="join-card"><div><span className="eyebrow">EXPERTISE MEETS PURPOSE</span><h3>Better, together.</h3><p>Universities, innovators, and partners.<br />One ecosystem for lasting change.</p><Link href="/universities">Meet the ecosystem <ArrowUpRight size={16} /></Link></div><div className="join-graphic" aria-hidden="true"><GraduationCap size={31} /><span><Users size={22} /></span><i><Lightbulb size={22} /></i></div></section></div>
  </div>;
}
