'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useState } from 'react';
import { LayoutDashboard, Compass, FolderKanban, GraduationCap, Handshake, ChartNoAxesCombined, HeartHandshake, Bell, Settings, CircleHelp, Search, ChevronDown, ArrowUpRight, ArrowRight, MapPin, Menu, X, Plus, LogOut, Leaf, Sparkles, Check } from 'lucide-react';
import { usePortal } from '@/components/providers/portal-provider';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { initials } from '@/lib/utils';

const navGroups = [
  { label: 'WORKSPACE', items: [['Overview', '/', LayoutDashboard], ['Explore challenges', '/challenges', Compass], ['My projects', '/projects', FolderKanban]] },
  { label: 'ECOSYSTEM', items: [['Universities & HEIs', '/universities', GraduationCap], ['Industry & partners', '/partners', Handshake], ['Analytics', '/analytics', ChartNoAxesCombined]] }
];
export default function PortalShell({ children }) {
  const pathname = usePathname(); const router = useRouter();
  const { user, demo, notifications, logout } = usePortal();
  const [mobileOpen, setMobileOpen] = useState(false); const [helpOpen, setHelpOpen] = useState(false); const [query, setQuery] = useState(''); const [profileOpen, setProfileOpen] = useState(false);
  const unread = notifications.filter(item => !item.read).length;
  const isAuth = ['/login', '/register'].includes(pathname);
  const isHome = pathname === '/';
  const section = isHome || ['/citizen', '/authority', '/university', '/partner', '/admin'].includes(pathname) ? 'Overview' : pathname.split('/')[1]?.replace(/-/g, ' ');
  return <div className={`app-shell ${isAuth ? 'auth-shell' : ''} ${isHome ? 'home-shell' : ''}`}>
    <a className="skip-link" href="#main-content">Skip to content</a>
    {mobileOpen && <button className="sidebar-backdrop" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}
    <aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}>
      <Link className="brand" href="/" onClick={() => setMobileOpen(false)}><span className="brand-symbol"><Leaf size={26} strokeWidth={1.8} /><span /></span><span><strong>Jharkhand<span>Innovation</span></strong><small>Ideas to impact.</small></span></Link>
      <button className="workspace-selector" onClick={() => router.push('/')}><span className="workspace-mark"><MapPin size={17} /></span><span><strong>Jharkhand ecosystem</strong><small>Societal Innovation Portal</small></span><ChevronDown size={15} /></button>
      <nav aria-label="Main navigation">{navGroups.map(group => <div className="nav-group" key={group.label}><p className="nav-label">{group.label}</p>{group.items.map(([label, href, Icon]) => <Link key={href} href={href} onClick={() => setMobileOpen(false)} className={`nav-item ${(href === '/' ? section === 'Overview' : pathname.startsWith(href)) ? 'active' : ''}`}><Icon size={19} strokeWidth={1.7} /><span>{label}</span>{href === '/challenges' && <span className="nav-new">NEW</span>}</Link>)}</div>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-invite"><span className="invite-icon"><Sparkles size={19} /></span><h4>A small step. A big change.</h4><p>Your community’s next solution<br />could start with you.</p><Link href="/report">Report a problem <ArrowUpRight size={15} /></Link></div><Link className={`nav-item ${pathname === '/notifications' ? 'active' : ''}`} href="/notifications"><Bell size={18} /><span>Notifications</span>{unread > 0 && <span className="unread-badge">{unread}</span>}</Link><Link className={`nav-item ${pathname === '/settings' ? 'active' : ''}`} href="/settings"><Settings size={18} /><span>Settings</span></Link><button className="nav-item help-button" onClick={() => setHelpOpen(true)}><CircleHelp size={18} /><span>Help & support</span><ArrowUpRight size={15} /></button><div className="sidebar-footer"><span className="live-dot" /> Building a better Jharkhand</div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="btn-icon mobile-menu" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><span className="breadcrumb">Workspace <span>/</span> <strong>{section}</strong></span></div><form className="global-search" onSubmit={event => { event.preventDefault(); router.push(`/challenges?q=${encodeURIComponent(query)}`); }}><Search size={16} /><input aria-label="Search challenges, people, or places" placeholder="Search challenges, people, or places..." value={query} onChange={event => setQuery(event.target.value)} /><kbd>↵</kbd></form><div className="topbar-actions"><span className="location-label"><MapPin size={14} /> Jharkhand, India</span><Link href="/notifications" className="notification-button" aria-label={`Notifications${unread ? `, ${unread} unread` : ''}`}><Bell size={19} />{unread > 0 && <i />}</Link><div className="profile-wrap"><button className="avatar-button" aria-label="Open account menu" aria-expanded={profileOpen} onClick={() => setProfileOpen(!profileOpen)}><span className="avatar">{initials(user?.name || 'Guest User')}</span><ChevronDown size={13} /></button>{profileOpen && <div className="profile-menu"><strong>{user?.name || 'Welcome, changemaker'}</strong><small>{user ? `${user.role} account${demo ? ' · demo' : ''}` : 'Explore the innovation ecosystem'}</small><Link href="/login" onClick={() => setProfileOpen(false)}>{user ? 'Switch demo role' : 'Sign in'} <ArrowRight size={14} /></Link><Link href="/settings" onClick={() => setProfileOpen(false)}>Profile & settings <Settings size={14} /></Link>{user && <button onClick={async () => { await logout(); setProfileOpen(false); }} >Sign out <LogOut size={14} /></button>}</div>}</div></div></header>
      <main id="main-content" className="main-content">{children}</main><footer className="main-footer"><span>© 2026 Jharkhand Innovation. Together, we make a difference.</span><span>{demo ? 'Demo workspace · Illustrative data' : 'Societal Innovation Collaboration Portal'}<span className="footer-dot">·</span><Link href="/">About the initiative <ArrowUpRight size={12} /></Link></span></footer>
    </div>
    <Dialog open={helpOpen} onOpenChange={setHelpOpen}><DialogContent><div className="icon-tile teal"><CircleHelp /></div><DialogTitle className="dialog-title">A little help to get started</DialogTitle><DialogDescription className="muted">Everyone has a part to play in a stronger Jharkhand.</DialogDescription><div className="help-steps">{[['Report a challenge', 'Describe the issue, attach evidence, confirm its location, and review the AI-assisted summary.'], ['Follow its progress', 'Open a challenge to see the team, milestones, discussion, and a complete activity timeline.'], ['Collaborate on a solution', 'Choose an authority, university, or partner demo account to try the full project lifecycle.'], ['Verify the difference', 'A resolution needs after-evidence, a location check, and authority approval.']].map(([title, text], i) => <div key={title}><span>{i + 1}</span><section><strong>{title}</strong><p>{text}</p></section></div>)}</div><Link className="btn btn-primary" href="/report" onClick={() => setHelpOpen(false)}>Report your first problem <ArrowRight size={16} /></Link></DialogContent></Dialog>
  </div>;
}
