import { z } from "zod";
import { categories, districts, priorities } from "../data/seed.js";

export const locationSchema = z.object({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), accuracy: z.number().min(0).max(100000).nullable().optional(), address: z.string().max(500).default(""), source: z.enum(["device", "gps", "exif", "manual", "map", "metadata", "search"]).default("manual"), confirmed: z.boolean().default(false), capturedAt: z.string().max(80).nullable().optional() });
export const questionSchema = z.object({ id: z.string().min(1).max(80), question: z.string().min(3).max(400), type: z.enum(["text", "number", "select"]).default("text"), options: z.array(z.string().max(200)).max(10).optional(), optional: z.boolean().optional() });
export const analysisSchema = z.object({ title: z.string().min(5).max(180), summary: z.string().min(10).max(2000), description: z.string().max(10000).optional(), category: z.enum(categories), subcategory: z.string().max(150).default(""), priority: z.enum(priorities), severity: z.enum(priorities), affectedPopulation: z.number().int().min(0).max(100000000).nullable().default(null), suggestedDepartments: z.array(z.string().max(150)).max(10).default([]), suggestedExpertise: z.array(z.string().max(150)).max(10).default([]), suggestedDisciplines: z.array(z.string().max(150)).max(10).default([]), solutionDomains: z.array(z.string().max(200)).max(10).default([]), contributingFactors: z.array(z.string().max(300)).max(10).default([]), followUpQuestions: z.array(questionSchema).max(6).default([]), observations: z.array(z.string().max(500)).max(10).default([]), missingInformation: z.array(z.string().max(300)).max(10).default([]), evidenceSummary: z.string().max(2000).default(""), imageDescription: z.string().max(3000).optional().default(""), isRelevant: z.boolean().default(true), relevanceReason: z.string().max(1000).optional().default("") });
const evidenceReference = z.object({ id: z.string().min(1).max(160), location: locationSchema.nullable().optional() });
export const analyzeSchema = z.object({ description: z.string().trim().min(15).max(10000), category: z.string().max(80).nullable().optional(), district: z.string().max(80).nullable().optional(), location: locationSchema.nullable().optional(), evidence: z.array(evidenceReference).max(12).default([]), answers: z.record(z.string(), z.union([z.string().max(2000), z.number(), z.array(z.string().max(500))])).default({}) });
export const problemSchema = z.object({ title: z.string().trim().min(8).max(180), description: z.string().trim().min(20).max(10000), summary: z.string().trim().min(10).max(2000).optional(), category: z.enum(categories), district: z.enum(districts), location: locationSchema.refine((value) => value.confirmed, "Please confirm the challenge location."), priority: z.enum(priorities).default("Medium"), severity: z.enum(priorities).default("Medium"), affectedPopulation: z.coerce.number().int().min(0).max(100000000).default(0), evidence: z.array(evidenceReference).max(12).default([]), aiAnalysis: z.object({ source: z.enum(["demo", "gemini"]).optional(), suggestedDepartments: z.array(z.string().max(150)).max(10).optional(), suggestedExpertise: z.array(z.string().max(150)).max(10).optional(), observations: z.array(z.string().max(500)).max(10).optional(), missingInformation: z.array(z.string().max(300)).max(10).optional(), evidenceSummary: z.string().max(2000).optional() }).passthrough().optional(), answers: z.record(z.string(), z.union([z.string().max(2000), z.number(), z.array(z.string().max(500))])).optional() });

export const allowedMimeTypes = ["image/jpeg", "image/png", "image/webp", "image/gif", "video/mp4", "video/webm", "video/quicktime", "application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "text/plain"];
export function maxFileSize(type) { return type?.startsWith("video/") ? 100 * 1024 * 1024 : type?.startsWith("image/") ? 10 * 1024 * 1024 : 20 * 1024 * 1024; }
export const uploadSchema = z.object({ fileName: z.string().trim().min(1).max(200), contentType: z.enum(allowedMimeTypes), size: z.number().int().positive(), phase: z.enum(["before", "after", "supporting"]).default("before"), problemId: z.string().regex(/^[a-zA-Z0-9-]{1,80}$/).optional() }).refine((value) => value.size <= maxFileSize(value.contentType), "File exceeds the limit: images 10 MB, videos 100 MB, documents 20 MB.");

export class ApiError extends Error { constructor(message, status = 400) { super(message); this.status = status; } }
export function parse(schema, body) {
  const result = schema.safeParse(body);
  if (!result.success) throw new ApiError(result.error.issues.map((issue) => `${issue.path.join(".") || "Request"}: ${issue.message}`).slice(0, 3).join(" "), 400);
  return result.data;
}
